### ISSUE TITLE
KeyError: '1' when running methgo snp

### ISSUE THREAD

**Issue by avilella** [paoyangchen-laboratory/methgo#1]
I tried running methgo snp with the command below, and got an error:

```
# /data/home/user/paoyangchen-laboratory-methgo-911acbc/methgo snp -g /data/home/user/genomes/Human/GRCh38/Homo_sapiens.GRCh38.dna.all.fa /data/group/test/TEST_Run001/TEST_Run001_bismark_hg38_samplebysample-12345678/WBGS_oxBS_vB_1000ng_PCR06_R02-12345678/WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.bam
Traceback (most recent call last):
  File "/data/home/user/paoyangchen-laboratory-methgo-911acbc/methgo", line 13, in <module>
    module.main()
  File "/data/home/user/paoyangchen-laboratory-methgo-911acbc/scripts/snp/snp.py", line 105, in main
    snpOutput(args.bamfile,args.genomeFile,args.coverage,args.majorAlleleFreq,args.buffer)
  File "/data/home/user/paoyangchen-laboratory-methgo-911acbc/scripts/snp/snp.py", line 75, in snpOutput
    refNuc = openFile[chr][pos]
  File "/data/home/user/.local/lib/python2.7/site-packages/pyfasta/fasta.py", line 128, in __getitem__
    c = self.index[i]
KeyError: '1'
```

Any ideas?

**Comment by wwliao** [comment]
Can you please check the FASTA file is the same file you used to generate the BAM file?
I guess it's a mismatch in chromosome names, e.g. one maybe use "chr1", but the other use "1".

**Comment by avilella** [comment]
Dear Wen-Wei Liao,

I ran a small example with these two input files:

https://cloud.curoverse.com/collections/download/qr1hi-4zz18-na0zghh5hrqpgcv/19b2plvcyblkufyh0c30y7q9ct0fmd63nln4zhcqqp6amas3yi/

```
$HOME/paoyangchen-laboratory-methgo-911acbc/methgo snp -g
$GROUP/Genomes/Human/hs38DH/hs38DH.karyotype.fa
WBGS-oxBS-vB-1000ng-PCR06-R02_S1_L001_R1_001.cutB_pe.sorted.mrgd.karyotype.bam
Traceback (most recent call last):
  File "/bi/home/rocks-av/paoyangchen-laboratory-methgo-911acbc/methgo",
line 13, in <module>
    module.main()
  File
"/bi/home/rocks-av/paoyangchen-laboratory-methgo-911acbc/scripts/snp/snp.py",
line 105, in main

snpOutput(args.bamfile,args.genomeFile,args.coverage,args.majorAlleleFreq,args.buffer)
  File
"/bi/home/rocks-av/paoyangchen-laboratory-methgo-911acbc/scripts/snp/snp.py",
line 71, in snpOutput
    for col in bam.pileup():
  File "pysam/calignmentfile.pyx", line 1066, in
pysam.calignmentfile.AlignmentFile.pileup (pysam/calignmentfile.c:12408)
ValueError: no index available for pileup
```

**Comment by wwliao** [comment]
Before you run SNP module in MethGo, the BAM file need to be indexed first (I'll update this info on the docs later):

$ samtools index your.bam

It'll generate a *.bam.bai in the same place of your BAM file.
After getting the index file, please try to run SNP module again.
